// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfnmOOI56xxSgWde8sstXxCgOdS_TF5OI',
    appId: '1:492941586062:web:94cf5ebc4490f5747563df',
    messagingSenderId: '492941586062',
    projectId: 'lp-task',
    authDomain: 'lp-task.firebaseapp.com',
    storageBucket: 'lp-task.firebasestorage.app',
    measurementId: 'G-VX6KLDFNME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmUYhc1kxD_yUCRKIptDZW6FyoQgIhKHg',
    appId: '1:492941586062:android:188ecc3ca0c593a07563df',
    messagingSenderId: '492941586062',
    projectId: 'lp-task',
    storageBucket: 'lp-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwa4ovI_cyg--UGJC1ebaYc6pYFZnc-bk',
    appId: '1:492941586062:ios:8b3a341d20572b4d7563df',
    messagingSenderId: '492941586062',
    projectId: 'lp-task',
    storageBucket: 'lp-task.firebasestorage.app',
    iosClientId: '492941586062-um16j2v11vdm4ild5ls91caaomn8bio8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lpTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwa4ovI_cyg--UGJC1ebaYc6pYFZnc-bk',
    appId: '1:492941586062:ios:8b3a341d20572b4d7563df',
    messagingSenderId: '492941586062',
    projectId: 'lp-task',
    storageBucket: 'lp-task.firebasestorage.app',
    iosClientId: '492941586062-um16j2v11vdm4ild5ls91caaomn8bio8.apps.googleusercontent.com',
    iosBundleId: 'com.example.lpTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfnmOOI56xxSgWde8sstXxCgOdS_TF5OI',
    appId: '1:492941586062:web:204b7fd9e5cd9acf7563df',
    messagingSenderId: '492941586062',
    projectId: 'lp-task',
    authDomain: 'lp-task.firebaseapp.com',
    storageBucket: 'lp-task.firebasestorage.app',
    measurementId: 'G-QJ9YFVS5FW',
  );
}
